### PR TITLE
Create LICENSE file

### PR DESCRIPTION
**Pull request by andrewdavidmackenzie**
Create a separate license file for reading by automated license checking tools

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks! Hope it helps you move forward with your workflow there.

**Comment by andrewdavidmackenzie** [comment]
Thanks!!

 I will grind my way through the others this week.

Then will look out for next release to npm registry, so our dependencies have the license file.

Cheers

**Comment by guybedford** [comment]
Sure the couple I checked seemed to be the same license - it's important to check the js file or repo from the browserify list at the browserify github page. Let me know if you need clarification finding these.

**Comment by andrewdavidmackenzie** [comment]
BTW: I noticed that (only) the -http lib has MIT license in it already...

**Pull request merged**
